services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - mwt_network

  backend:
    build:
      context: ./backend
    volumes:
      - static_volume:/app/static_collected
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=builder.mwt.one,backend
    depends_on:
      - db
    networks:
      - mwt_network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://builder.mwt.one
    networks:
      - mwt_network

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - static_volume:/app/static_collected
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - mwt_network

  certbot:
    image: certbot/certbot
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - mwt_network

networks:
  mwt_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  certbot_conf:
  certbot_www:
