services:
  db:
    image: postgres:16-alpine
    container_name: mwt-builder-postgres
    volumes:
      - mwt_builder_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - mwt_builder_network

  django:
    build:
      context: ./backend
    image: mwt-builder/django:latest
    container_name: mwt-builder-django
    volumes:
      - mwt_builder_static:/app/static_collected
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=builder.mwt.one,django,187.77.218.102
    depends_on:
      - db
    networks:
      - mwt_builder_network

  frontend:
    build:
      context: ./frontend
    image: mwt-builder/frontend:latest
    container_name: mwt-builder-frontend
    networks:
      - mwt_builder_network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: mwt-builder/nginx:latest
    container_name: mwt-builder-nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - mwt_builder_static:/app/static_collected
      - mwt_builder_certbot_conf:/etc/letsencrypt
      - mwt_builder_certbot_www:/var/www/certbot
    depends_on:
      - django
      - frontend
    networks:
      - mwt_builder_network

  certbot:
    image: certbot/certbot
    container_name: mwt-builder-certbot
    volumes:
      - mwt_builder_certbot_conf:/etc/letsencrypt
      - mwt_builder_certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - mwt_builder_network

networks:
  mwt_builder_network:
    driver: bridge

volumes:
  mwt_builder_postgres_data:
  mwt_builder_static:
  mwt_builder_certbot_conf:
  mwt_builder_certbot_www:
